// <auto-generated />
using System;
using CatalogRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogRepository.Migrations
{
    [DbContext(typeof(BrandRepository))]
    partial class BrandRepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogModel.Models.BrandModels.BrandModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2e86bd9e-9501-4e6a-858c-2860d2b17447"),
                            Name = "Brand 1"
                        },
                        new
                        {
                            Id = new Guid("8532df4f-0948-44f4-80a2-e9964481f9cd"),
                            Name = "Brand 2"
                        },
                        new
                        {
                            Id = new Guid("9e59e896-a35a-47cc-a977-0a01f96f8fbf"),
                            Name = "Brand 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
