// <auto-generated />
using System;
using CatalogRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogRepository.Migrations.TypeRepositoryMigrations
{
    [DbContext(typeof(TypeRepository))]
    [Migration("20260502162603_Types")]
    partial class Types
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogModel.Models.TypeModels.TypeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50b0c6cf-8c91-4d4a-b73f-0e68478f0936"),
                            Name = "Television"
                        },
                        new
                        {
                            Id = new Guid("6985420c-9586-4477-8e1c-76572eaf6610"),
                            Name = "Mobile"
                        },
                        new
                        {
                            Id = new Guid("2e66ef38-37fc-40fb-9339-48d0359a05e6"),
                            Name = "Fridge"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
